### ISSUE TITLE
Some infrastructures stay listed after deleting 

### ISSUE THREAD

**Issue by BorjaEst** [grycap/im-dashboard#25]
Hi,

After trying to deploy some infrastructures, (with failure due to site issues), I cannot delete the infrastructures from "My Infrastructures" list.

![Screenshot from 2020-06-02 10-01-24](https://user-images.githubusercontent.com/47473455/83495658-48c48d80-a4b8-11ea-8f2d-1ecb1def6b2f.png)
 
After presing "Delete" button, the "infrastructure uuid" stills there.
BR, Borja

**Comment by micafer** [comment]
Hi @BorjaEst,

If the infrastructure remains is because the IM cannot delete it successfully.
Could you tell me which site are you using.
There are some known issues in IFCA site deleting Security Groups that causes this kind of error.
You can delete it some hour before.

**Comment by micafer** [comment]
In case the infrastructure cannot be deleted for some error in the cloud provider. The IM service enables forcing the deletion. I'm adding this feature to the dashboard (see #26).

**Comment by BorjaEst** [comment]
Hi @micafer 

> Could you tell me which site are you using.
1. Provider: | OpenStack: controller.ceta-ciemat.es:5000
2. Provider: | OpenStack: keystone3.ui.savba.sk:5000 (x3)

> There are some known issues in IFCA site deleting Security Groups that causes this kind of error.
Does the IM delete the security groups if all instances are removed?
In keystone3.ui.savba.sk I tested again, but it did not get to create the groups (maybe that is the issue why it failed to deploy).

> You can delete it some hour before.
I tried it, but still there.

I have tried the force delete but the lines still there...

**Comment by micafer** [comment]
First one is CETA-CIEMAT, second one is IISAS.
IISAS has othe known issues that uses an old OpenStack API version. I will try to see how to configure it in the dashboard to enable it.

But forcing the deletion they should disappear.

**Comment by micafer** [comment]
IISAS error must be solved. Now you must be abe to submit and delete without errors.

**Comment by BorjaEst** [comment]
Hi @micafer,

I tried to delete the infrastructures and this time it worked perfectly.
Thank you!
