### ISSUE TITLE
kubeapps_endpoint in Outputs

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#315]
Hi,

When selecting https://appsgrycap.i3m.upv.es:31443/im-dashboard/configure?selected_tosca=kubernetes.yaml if `Flag to set the kubeapps UI to be installed` in `Kubernetes Data` is set to `False`, `kubeapps_endpoint` listed in the `Outputs` returns a `404` as expected.

Should `kubeapps_endpoint` not be listed in the `Outputs` when this flag is set to `False`?

Best regards,
Sebastian

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

I already changed it, and install kubeapps in the same way as other K8s "extras".
In this way the output is not shown if it is not selected.

Best regards.

**Comment by sebastian-luna-valero** [comment]
Great idea, thank you very much!

**Comment by micafer** [comment]
Updated.

**Comment by sebastian-luna-valero** [comment]
Thanks!
