### ISSUE TITLE
Remove nodes

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#323]
Hi,

Having the `Add nodes` option in IM Dashboard is great.

Would it be possible to have the opposite? i.e. `Delete nodes` (or similar)

Best regards,
Sebastian

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

It is already possible. You have to select one of the VMs, and in the VM Info page, select the "Terminate" option:

https://docs.egi.eu/users/compute/orchestration/im/dashboard/#vm-info-page

Best regards.

**Comment by sebastian-luna-valero** [comment]
Thanks!

But this would imply removing nodes one by one, right?

Would it be possible to remove them in groups?

Best regards,
Sebastian

**Comment by micafer** [comment]
> But this would imply removing nodes one by one, right?

Yes.

> Would it be possible to remove them in groups?

I will make it in next releases.

**Comment by sebastian-luna-valero** [comment]
Brilliant, thank you very much!

**Comment by sebastian-luna-valero** [comment]
Thanks @micafer 

I tested it with a virtual k8s cluster. I can successfully delete VMs by selecting them from the menu. VMs are removed both from IM Dashboard and OpenStack. However, inside k8s, the deleted nodes appear as `NotReady`. I guess that's expected.

Thanks for adding this functionality!

**Comment by sebastian-luna-valero** [comment]
An additional comment regarding:

> It is already possible. You have to select one of the VMs, and in the VM Info page, select the "Terminate" option:

In the VM Info page, should `Terminate` button be named `Delete`? So the name of the button is consistent in both the infrastructure view and the VM Info page. It would also help if they both have the same icon.

**Comment by sebastian-luna-valero** [comment]
Looks great, thanks!
