### ISSUE TITLE
Friendly names created on OpenStack

### ISSUE THREAD

**Issue by EGI-ILM** [grycap/im-dashboard#355]
When using the IM with OpenStack, the instances created on OpenStack are prefixed with "wn", "front", "simple-node", etc:

```
wn-ad43714-39ac-11ed-...
front-bbbbfa4a-2534-...
wn-bbbbb134-2534-11ed-...
wn-ad43714-39ac-11ed-...
wn-ad43714-39ac-11ed-...
wn-ad43714-39ac-11ed-...
simple-node-49ff712-2f80-11ed-...
wn-cdcfb124-2f14-11ed-...
front-cdc6c640-29ac-11ed-...
```

This makes a bit complicated to identify which deployment is which from OpenStack, on a first sight, as the user has to go back and forth to copy IDs and search for them in OpenStack.

It would be useful if the nodes created use a sanitised version of the friendly name given to the deployment by the user on IM. Example:

```
datawarehouse-wn-ad43714-39ac-11ed-...
datawarehouse-fn-bbbbfa4a-2534-...
mycluster-wn-bbbbb134-2534-11ed-...
mycluster-wn-ad43714-39ac-11ed-...
mycluster-wn-ad43714-39ac-11ed-...
mycluster-wn-ad43714-39ac-11ed-...
project1_datalake-49ff712-2f80-11ed-...
```

If the user changes the name of the IM deployment, it could ideally be reflected in OpenStack. However, even if this is not possible and the original name of the instance that was given on creation is maintained on OpenStack, it is still useful.

**Comment by micafer** [comment]
Deployed in the devel instance.
@EGI-ILM could you test it?

**Comment by EGI-ILM** [comment]
Looks good to me:
![image](https://user-images.githubusercontent.com/97176673/199018510-e63e03ad-38a5-4b41-b5b2-0ebff573adae.png)

![image](https://user-images.githubusercontent.com/97176673/199017782-8810227e-b06c-4495-889a-d47a57daf0e4.png)

The only addition perhaps is to use the identifier in other elements, such as the **Security Groups**. Maybe there is a reason to keep the **infrastructure ID** as Security Group name, but perhaps it can be prefixed too.

![image](https://user-images.githubusercontent.com/97176673/199018438-b0e8b1a5-7645-4fa6-a4d2-f569a83b2638.png)
