### ISSUE TITLE
Minimum number of nodes with elastic k8s clusters with ec3

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#359]
Hello,

When selecting the elastic k8s option in [IM Dashboard](https://im.egi.eu/im-dashboard/configure?selected_tosca=kubernetes.yaml&childs=kubernetes_elastic.yaml), the `Elastic Data` allows to configure the `Maximum Number of WNs in the cluster`

![image](https://user-images.githubusercontent.com/5345517/193234052-ad184391-6ce5-4969-9bb6-db1bb0e7b408.png)

I think `ec3` also supports to have a minimum number of WNs in the cluster (e.g. in preparation for a peak workload). Could you please confirm? If so, would it be possible to add this option to the IM dashboard too?

Thanks!
Sebastian

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

EC3 uses CLUES(https://github.com/grycap/clues) as the elastic management system.
Some of the options of CLUES is to keep extra empty slots or nodes free.

I will check how to add it to the IM-Dashboard.

**Comment by micafer** [comment]
I have added the option in the IM-Dashboard.
Could you test it please?

**Comment by sebastian-luna-valero** [comment]
Thanks!

Not sure if it's related but on a test deployment I am currently getting:
```
fatal: [78.128.251.47_0]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip2", "install", "ply", "radl", "jaraco.functools==3.4.0", "more-itertools==5.0", "web.py==0.51", "requests==2.15.1", "PyYAML==5.4.1", "distro", "git+https://github.com/grycap/cpyutils.git@master"], "msg": "stdout: Collecting git+https://github.com/grycap/cpyutils.git@master\n Cloning https://github.com/grycap/cpyutils.git (to master) to ./pip-Pt1VQC-build\nCollecting ply\n Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)\nCollecting radl\n Downloading https://files.pythonhosted.org/packages/8a/a2/620e4bed32f849759014cfd3a3390dae0bc8709a559052b77cf9f7292f79/RADL-1.3.0.tar.gz\nCollecting jaraco.functools==3.4.0\n\n:stderr: Could not find a version that satisfies the requirement jaraco.functools==3.4.0 (from versions: 1.0, 1.1, 1.2, 1.3, 1.4, 1.4.1, 1.5, 1.6, 1.7, 1.8, 1.8.1, 1.8.2, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.15.1, 1.15.2, 1.16, 1.17, 1.18, 1.19, 1.20, 2.0)\nNo matching distribution found for jaraco.functools==3.4.0\n"}
```

**Comment by micafer** [comment]
> Not sure if it's related but on a test deployment I am currently getting:
> 
> ```
> fatal: [78.128.251.47_0]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip2", "install", "ply", "radl", "jaraco.functools==3.4.0", "more-itertools==5.0", "web.py==0.51", "requests==2.15.1", "PyYAML==5.4.1", "distro", "git+https://github.com/grycap/cpyutils.git@master"], "msg": "stdout: Collecting git+https://github.com/grycap/cpyutils.git@master\n Cloning https://github.com/grycap/cpyutils.git (to master) to ./pip-Pt1VQC-build\nCollecting ply\n Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)\nCollecting radl\n Downloading https://files.pythonhosted.org/packages/8a/a2/620e4bed32f849759014cfd3a3390dae0bc8709a559052b77cf9f7292f79/RADL-1.3.0.tar.gz\nCollecting jaraco.functools==3.4.0\n\n:stderr: Could not find a version that satisfies the requirement jaraco.functools==3.4.0 (from versions: 1.0, 1.1, 1.2, 1.3, 1.4, 1.4.1, 1.5, 1.6, 1.7, 1.8, 1.8.1, 1.8.2, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.15.1, 1.15.2, 1.16, 1.17, 1.18, 1.19, 1.20, 2.0)\nNo matching distribution found for jaraco.functools==3.4.0\n"}
> ```

No it was an error in the CLUES ansible role.
Now it is fixed.

**Comment by sebastian-luna-valero** [comment]
Thanks!

I chose the following in my test deployment:

HW Data
* N of worker nodes 4

Elastic data
* Max number of WNs: 6
* Min number of WNs: 2

The cluster ends up having 4 nodes instead of 2. Is this expected?

**Comment by micafer** [comment]
As you have selected 4 worker nodes, initially the cluster will have 4 WNs. 
After some time, some will be undeployed to maintain the minimun number of nodes free to 2.

**Comment by sebastian-luna-valero** [comment]
Great, thanks!
Let's consider this solved then.
