### ISSUE TITLE
No package matching 'openssl-blacklist' is available

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#374]
Hi,

I am deploying a slurm cluster with Debian 11 and I get:
```
TASK [grycap.slurm : install slurm dependences in Deb systems] *****************
Thursday 24 November 2022 07:24:56.683023
fatal: [192.168.0.115_7]: FAILED! => {"changed": false, "msg": "No package matching 'openssl-blacklist' is available"}
```

Google takes me to: https://tracker.debian.org/pkg/openssl-blacklist

Should this dependency be removed from the TOSCA template?

Best regards,
Sebastian

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

It was an error in the slurm ansible role.
Coudl you test it again?

**Comment by sebastian-luna-valero** [comment]
It works now, many thanks!
