### ISSUE TITLE
Single VM deployment specifying flavor name

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#381]
Hello,

When deploying a [kubernetes cluster](https://im.egi.eu/im-dashboard/configure?selected_tosca=kubernetes.yaml), I see this handy option: `Flavor name of the front-end node. Only required in case of special flavors (i.e. with GPUs) `

Would it be possible to have this option as well when deploying a single [VM](https://im.egi.eu/im-dashboard/configure?selected_tosca=simple-node-disk.yml)?

Sometimes the flavors offered by a site do not match the combination of CPUs/RAM from the drop-down menus, and with this option you can specifically choose which VM flavor to use.

Many thanks,
Sebastian

**Comment by micafer** [comment]
Done!

**Comment by sebastian-luna-valero** [comment]
Hi!

Sorry, could you also add this option to the TOSCA template for Slurm?

Best regards,
Sebastian

**Comment by micafer** [comment]
For both FE and WNs?

**Comment by sebastian-luna-valero** [comment]
If possible, yes, please.

**Comment by micafer** [comment]
Done.

**Comment by sebastian-luna-valero** [comment]
Hi,

I see that the option to specify a particular flavor for the deployment of [simple-node-disk.yml](https://github.com/grycap/tosca/blob/main/templates/simple-node-disk.yml) is no longer available.

Is there a reason? or can this be added back?

Thanks,
Sebastian

**Comment by micafer** [comment]
It has been added in the devel instance.

**Comment by sebastian-luna-valero** [comment]
Thanks! 

I have just tested it, and selecting the specific flavor overrides CPU and RAM, but not the size of the root disk. Perhaps it should?

Also please update ` Size of the root disk of the WNs ` with ` Size of the root disk of the VM`

Thanks!
