### ISSUE TITLE
Reconfigure single VM in a cluster

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#382]
Hello,

When I deploy a k8s cluster sometimes the configuration fails for only one of the nodes. With IM dashboard I can go and look at the individual node details (e.g. log):

![image](https://user-images.githubusercontent.com/5345517/208091531-fda393f9-6877-45cb-949c-03f23dd43b89.png)

The problem is that when I click `Reconfigure` on the menu for one VM, it seems that the reconfiguration starts for all the nodes in the cluster.

Is this expected?

Best regards,
Sebastian

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

Some basic steps are always made in all the nodes in all the cases.

**Comment by sebastian-luna-valero** [comment]
Thanks for confirming, @micafer 

Not an issue, then!
