### ISSUE TITLE
Issue deploying Galaxy + Slurm

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#384]
Hi,

Using: https://im.egi.eu/im-dashboard/configure?selected_tosca=slurm_cluster.yml&childs=galaxy.yaml

I get the error:
```
Error creating infrastrucrure: Error Creating Inf.: 'Node template "simple_node" was not found in "local_lrms".'.
```

Could you please have a look?

Thanks,
Sebastian

**Comment by micafer** [comment]
Fixed. It was an error in the name of the child template.

**Comment by sebastian-luna-valero** [comment]
Hi,

Could you also update the link: 
https://im.egi.eu/im-dashboard/configure?selected_tosca=slurm_cluster.yml&childs=slurm_galaxy.yaml

To:
https://im.egi.eu/im-dashboard/configure?selected_tosca=slurm_cluster.yml&childs=slurm_galaxy.yml

In `Deploy a Galaxy portal in the SLURM cluster`:
![image](https://user-images.githubusercontent.com/5345517/208862855-8a001631-2074-4842-aefb-db681a3e57fe.png)

Thanks,
Sebastian

**Comment by sebastian-luna-valero** [comment]
I tried several times to deploy Galaxy + Slurm but I get the following error messages on all the worker nodes:
```
Error launching the contextualization agent to configure the VM. Check the SSH connection.
```

Infrastructure uuid is `06a52101-810f-11ed-84d3-6ee17b71464b`

What could be the reason?

Many thanks,
Sebastian

**Comment by micafer** [comment]
Could you tell me what site and VM image are you using?

**Comment by sebastian-luna-valero** [comment]
The error above was on GSI-LCG2 using Ubuntu 20.04 from AppDB.

I re-tried at CESNET with the same VMI and I am now getting
```
Error adding a floating IP: Error attaching a Floating IP to the node.
Error adding a floating IP: Max number of retries reached.
```
but I can manually create and attach floating IPs from Horizon dashboard.

**Comment by micafer** [comment]
CESNET floating IP error is related to the combination of private and public IP set

```
Not Found External network 08b3fb96-6e2d-455b-8f9a-747da99689f2 is not reachable from subnet f60e919e-d554-4b5a-8f1a-6001f7cdb0bb.  Therefore, cannot associate Port 6ce89c27-701c-426f-a637-3e1270353bc4 with a Floating IP
```

**Comment by sebastian-luna-valero** [comment]
That's strange, I am using https://github.com/grycap/im-dashboard/blob/master/sites.json#L31

Deployments for other topologies on that <vo,site> work as expected.

**Comment by micafer** [comment]
In the private network you have "auto_allocated_network" instead of the name of a concrete network. Why you do not set a particular network name (as done in the other VOs)?

**Comment by sebastian-luna-valero** [comment]
Hi,

If I deploy:
https://im.egi.eu/im-dashboard/configure?selected_tosca=kubernetes.yaml

and:
https://im.egi.eu/im-dashboard/configure?selected_tosca=simple-node-disk.yml

instead of:
https://im.egi.eu/im-dashboard/configure?selected_tosca=slurm_cluster.yml&childs=slurm_galaxy.yml

at CESNET using the `training.egi.eu` VO the deployments work and the network configuration is the same:
https://github.com/grycap/im-dashboard/blob/master/sites.json#L31

Do you know why it fails only for the slurm template?
