### ISSUE TITLE
Adding OpenStack credentials

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#395]
Hi,

I would like to add OpenStack credentials in https://im.egi.eu/im-dashboard/manage_creds

![image](https://user-images.githubusercontent.com/5345517/214053254-8f047c1e-1035-4989-8588-87a2f85218fa.png)

But I am getting:

```bash
Error getting cloud info: 'Invalid credentials with the provider'
```

I think I using correct values but I don't know how to proceed.

Also, I checked https://imdocs.readthedocs.io/en/latest/dashboard.html#cloud-credentials but I miss specific details for OpenStack credentials.

Could you please help?

Thanks,
Sebastian

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

Check Authorization file info in IM docs:

https://imdocs.readthedocs.io/en/latest/client.html#authorization-file

**Comment by sebastian-luna-valero** [comment]
It looks like the OpenStack site that I am working with requires `v3oidcpassword` for  `auth_version`:

https://docs.openstack.org/python-openstackclient/latest/cli/man/openstack.html#envvar-OS_AUTH_TYPE

I don't see that supported by IM, right?

> auth_version the auth version used to connect with the Keystone server. The possible values are: 2.0_password, 2.0_voms, 3.x_password or 3.x_oidc_access_token. The default value is 2.0_password.

That would explain why I can't get it to work.

**Comment by micafer** [comment]
Yes, currently `v3oidcpassword` auth method is not supported at IM level.

**Comment by sebastian-luna-valero** [comment]
ok, thanks for confirming.
