### ISSUE TITLE
TOSCA output for MinIO deployment in k8s

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#398]
Hi,

I have been testing the MinIO deployment in k8s with IM:
https://im.egi.eu/im-dashboard/configure?selected_tosca=kubernetes.yaml&childs=minio.yaml

The `minio_endpoint` output has a couple of issues:
* it points to the S3 endpoint rather than the console endpoint
* it points to `https` but it's rather `http` at the moment.

Just in case you would like to update it.

Other than that, many thanks for providing this as it's a great way to test it!

Best regards,
Sebastian

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

I have updated the MinIO recipe, it works now with https and now show both URLs (API and console).

**Comment by sebastian-luna-valero** [comment]
Thank you very much @micafer
