### ISSUE TITLE
Enable the users to deploy their own tosca template

### ISSUE THREAD

**Issue by micafer** [grycap/im-dashboard#425]

**Comment by sebastian-luna-valero** [comment]
Thank you very much, this is a great addition!

So far I only see the option to paste the TOSCA template into a text box. On top of that, it would be nice to have the option to simply specify a URL to download the TOSCA template (i.e. from a public GitHub repository).

What do you think?

**Comment by micafer** [comment]
It is an interesting feature. We will try to add it in next releases.

**Comment by sebastian-luna-valero** [comment]
Thank you very much!
