### ISSUE TITLE
Reconfiguring credentials after deployment

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#484]
Hi,

Say that I deploy HTCondor with Pulsar [using IM Dashboard](https://im.egi.eu/im-dashboard/configure?selected_tosca=htcondor_cluster.yml&childs=pulsar.yml). For that I need to provide credentials.

Imagine that after the deployment I want to change the credentials provided to Pulsar. I can do this manually via CLI but would it be possible to click `Reconfigure` in IM Dashboard and provide the new credentials?

Many thanks!
Sebastian

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

You can do it with the im-client, but now it is not possible to do it with the IM Dashboard.

Best regards.

**Comment by sebastian-luna-valero** [comment]
Thanks for confirming @micafer

**Comment by sebastian-luna-valero** [comment]
Hi,

On second thoughts, here is a random idea.

Once Pulsar is deployed, in `Actions` the drop down menu shows the following options:

![image](https://github.com/grycap/im-dashboard/assets/5345517/2e194579-3c47-4939-a16b-0c27ddd4054b)

Would it be possible to click on `Reconfigure` and in the pop up menu have an option with:

![image](https://github.com/grycap/im-dashboard/assets/5345517/5a3ec3ca-c513-4a13-a681-35020cffedb3)

Or is this very hard to implement?

Many thanks,
Sebastian

**Comment by micafer** [comment]
We can take a look on this.

**Comment by sebastian-luna-valero** [comment]
Great, thank you very much!

**Comment by bgruening** [comment]
Awesome!!!
