### ISSUE TITLE
Wrong VO-Project target when creating infrastructure

### ISSUE THREAD

**Issue by BorjaEst** [grycap/im-dashboard#51]
When deploying a K8 cluster, I selected VO: "o3as"

However the master was created in the project scope "eosc-synergy" wich I noticed it is the one configured at my service credentials.

The application should not deploy the infrastructure on a different VO project as it would be difficult to find out where it was created (when you belong to several VO).

Also, when I try to edit my project at service credentials, it does not allow me to select my other VO.
![image](https://user-images.githubusercontent.com/47473455/93069940-8cfe2700-f67e-11ea-8f82-501f60e5e202.png)

## Extra info
I belong to:
![image](https://user-images.githubusercontent.com/47473455/93069975-98515280-f67e-11ea-9aa6-bf6e26584d1f.png)

Related #33

**Comment by micafer** [comment]
The list of VOs shown by the Dashboard is obtained from the AppDB.
It is still a devel feature, and there is a lot of sites that does not publish this information.
So in many sites I have to add this information to an internal configuration file. In fact is this file: (https://github.com/grycap/im-dashboard/blob/master/sites.json).
So tell me the site name and the project name and ID in the OpenStack site so I can add it.

**Comment by BorjaEst** [comment]
Thank you Miguel,

The update would be:
```json
    {
        "name": "CESGA",
        "url": "https://fedcloud-osservices.egi.cesga.es:5000",
        "id": "11548G0",
        "vos": {
            "eosc-synergy.eu": "57bcb0efcba4467fa225add92fdc194c",
            "o3as.data.kit.edu": "4a22f140a5fb4678aa1599fbf0b44b2f"
            "covid19.eosc-synergy.eu": "972298c557184a2192ebc861f3184da8"
        }
    },
```
I will point to all sites this Tuesday that they have to update the file.
@marcvs

**Comment by micafer** [comment]
I have updated the file.
The VO should appear now in the dashboard.
