### ISSUE TITLE
Improve ID in cloud credentials

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#548]
Hi,

Could we add a help text to the ID field when adding a new EGI Check-in credential via: https://im.egi.eu/im-dashboard/manage_creds

![image](https://github.com/grycap/im-dashboard/assets/5345517/f179e99c-e2cf-4d50-9de4-74187711d3fa)

This is sometimes confusing for the end user, and they don't know what to include there.

Another idea is that this ID could be automatically set by using the VO and the provider selected. For example for the `vo.access.egi.eu` VO and `IISAS-FedCloud`, the ID could automatically be saved with e.g. `vo.access.egi.eu-IISAS-FedCloud` 

What do you think?

**Comment by maikenp** [comment]
Thanks - automatic filling would be good, but still nice to have help, in case the user wants to change the default filled value. 

Another request: 
<img width="1004" alt="Screenshot 2024-05-15 at 12 47 35" src="https://github.com/grycap/im-dashboard/assets/22190352/b813c5e0-744a-4a56-9c36-f64ebe916d3e">

the text says: "Select only one of this options AppDB or Site image:" 
that is easy to miss - and gives strange errors in the provisioning (like starting debian flavour machine although you selected almalinux 9) 
could you make the other box be unselectable if one is selected?

**Comment by micafer** [comment]
Help test added.
Available in the devel instance.

**Comment by sebastian-luna-valero** [comment]
From my point of view, that's perfect, many thanks!

@maikenp do you want to provide further feedback before we close this issue?

**Comment by maikenp** [comment]
Thansk - I could not get the help although I cleaned my cache in the browser. So I will trust you @sebastian-luna-valero  :)

**Comment by sebastian-luna-valero** [comment]
Thanks Miguel and Maiken!

**Comment by micafer** [comment]
Thank you both for your suggestions!

**Comment by sebastian-luna-valero** [comment]
Hi, could this be added to IM-prod, please?

**Comment by micafer** [comment]
done
