### ISSUE TITLE
Specify what types of SSH key are supported

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#549]
Hi,

Public SSH keys are checked when added via IM Dashboard: https://im.egi.eu/im-dashboard/ssh_keys

![image](https://github.com/grycap/im-dashboard/assets/5345517/e5e2416d-3622-4772-b9e2-e8c045b66a8c)

Following:

https://github.com/grycap/im-dashboard/blob/v2.5.6/app/ssh_key.py#L80

It looks like only public SSH keys of type RSA are supported?

If yes, could this be specified as help text in the form to add the SSH key to IM Dashboard?

Thanks to @maikenp for reporting.

Best regards,
Sebastian

**Comment by micafer** [comment]
We will improve the SSH key validation to support another formats.

**Comment by micafer** [comment]
Support for other formats added.
It is available in the devel instance.

**Comment by sebastian-luna-valero** [comment]
Tested it and it works, many thanks!
