### ISSUE TITLE
Make AppDB or Site image unselectable if the other one is selected

### ISSUE THREAD

**Issue by micafer** [grycap/im-dashboard#550]
Thanks - automatic filling would be good, but still nice to have help, in case the user wants to change the default filled value. 

Another request: 
<img width="1004" alt="Screenshot 2024-05-15 at 12 47 35" src="https://github.com/grycap/im-dashboard/assets/22190352/b813c5e0-744a-4a56-9c36-f64ebe916d3e">

the text says: "Select only one of this options AppDB or Site image:" 
that is easy to miss - and gives strange errors in the provisioning (like starting debian flavour machine although you selected almalinux 9) 
could you make the other box be unselectable if one is selected?

_Originally posted by @maikenp in https://github.com/grycap/im-dashboard/issues/548#issuecomment-2112179536_

**Comment by micafer** [comment]
This is implemented and available in devel instance.
@maikenp and @sebastian-luna-valero could you test it please?

**Comment by maikenp** [comment]
Tried it, super!

**Comment by sebastian-luna-valero** [comment]
Works great, many thanks!

**Comment by sebastian-luna-valero** [comment]
Hi, reminder to move this to IM-prod as well.

**Comment by micafer** [comment]
done
