### ISSUE TITLE
Change status name in IM Dashboard

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-dashboard#559]
Hi,

As discussed with @maikenp, a correct deployment in IM Dashboard transitions among these states:
1. `pending`
2. `running`
3. `configured`

Would it be possible to rename `running` to `deploying`?

`running` gives the impression that the deployment is up and running. However the user should wait until `configured` appears before connecting to the virtual infrastructure (i.e. deployment completed). Otherwise, Ansible will still be configuring things.

Best regards,
Sebastian

**Comment by micafer** [comment]
This a discussion that I also have with other users, but I prefer to use "configuring" instead of "deploying".
What do yo think?

**Comment by sebastian-luna-valero** [comment]
True, `configuring` sounds appropriate as well. Thanks!

**Comment by sebastian-luna-valero** [comment]
Many thanks!
