### ISSUE TITLE
Include direct link to helpdesk

### ISSUE THREAD

**Issue by chbrandt** [grycap/im-dashboard#566]
If the user faces any issue and want to create a ticket (s)he must go to `External links > EGI IM-Dashboard Docs`, and, then, to `Support` (at the top-right navbar); Click-through a couple of pages (including HTTP "not secure" warning) until (s)he can finally login to GGUS. *Then* create the ticket...

Hidden. Cumbersome. Too much... By the third click the user has given up, and we lost the chance to improve.

**Initial proposal:** There should be a direct link (to GGUS / open ticket) from the IM-Dashboard. For starter, it could be in the bottom bar, a little 🐞 there, next to Github' Octocat would do a great service, I believe.

**Comment by micafer** [comment]
@chbrandt you can test it in the IM instance.

**Comment by chbrandt** [comment]
@micafer I just checked and I liked. Thank you for the improvement.
