### ISSUE TITLE
Consistent order of infrastructures

### ISSUE THREAD

**Issue by enolfc** [grycap/im-dashboard#581]
The order of infrastructures is not stable in the dashboard, it may change when refreshing or when performing actions. Even when the order is forced this order is lost when performing an action.
See sample video:

https://www.loom.com/share/20cdab8cb96544b3a7bb8f31dc7d6442?sid=db555271-0307-4e54-8c42-f78fcc56c683

It would be good to have a consistent order of infrastructures to avoid performing unwanted actions on infrastructures

**Comment by micafer** [comment]
It is a weird side effect of using DataTables ordering option. We should have to disable this option to avoid this problem.
Probably we'll do it.

**Comment by micafer** [comment]
It is implemented in the devel instance, could you check?
