### ISSUE TITLE
Discard providers that would not work with your selected VO

### ISSUE THREAD

**Issue by BorjaEst** [grycap/im-dashboard#80]
According to #33, when you select a VO and a Provider to deploy a TOSCA, it might happen that you get the error "Error loading images: Project __ not found".

This is quite confusing for users, normally they do not know that they HAVE to configure/change the project-site at the "Service Credentials" page. 

Would it be possible to?

1. Configure the field "Select provider" to display ONLY the sites where you configured the selected VO.

2. Create a note+link bellow "Select provider" to open a new tab on "Service Credentials", something similat to:
*If your provider is not listed, please configure your "[Service Credentials](https://appsgrycap.i3m.upv.es:31443/im-dashboard/manage_creds)" for the site.*

3. If a wrong VO was selected, rise an error! A log only saying "Error image not found" is not sufficient for the user.  

I think that would simplify the user experience (at list for those with multiple VO).

### How to reproduce

1. You need to belong to at least 2 VO (let's call VO1 & VO2)
2. You need to have at least 1 site supporting those 2 VO (let's call it YOUR-SITE)
3. Go to [Service Credentials](https://appsgrycap.i3m.upv.es:31443/im-dashboard/manage_creds) and EDIT "Manage your credential" at the YOUR-SITE to work with VO1.
4 Select any TOSCA templete to configure a deployment (Any)
5. Do a normal configuration that would normally work.
6. In the tab "Scheduling" select the VO2 and the provider "YOUR-SITE".
7. Submit.

### Deployment log example:
```
2020-11-12 09:06:38.223942: All VMs failed. No contextualize.
2020-11-12 09:06:44.295493: Error launching the VMs of type front to cloud ID ost3 of type OpenStack. Attempt 1: Error: 404 Not Found {'message': 'No image found with ID 8a32deca-1e5c-4d46-919d-b01b1f52e9b9

\n\n\n', 'code': '404 Not Found', 'title': 'Not Found'}
Attempt 2: Error: 404 Not Found {'message': 'No image found with ID 8a32deca-1e5c-4d46-919d-b01b1f52e9b9

\n\n\n', 'code': '404 Not Found', 'title': 'Not Found'}
Attempt 3: Error: 404 Not Found {'message': 'No image found with ID 8a32deca-1e5c-4d46-919d-b01b1f52e9b9

\n\n\n', 'code': '404 Not Found', 'title': 'Not Found'}

Error launching the VMs of type wn to cloud ID ost3 of type OpenStack. Attempt 1: Error: 404 Not Found {'message': 'No image found with ID 8a32deca-1e5c-4d46-919d-b01b1f52e9b9

\n\n\n', 'code': '404 Not Found', 'title': 'Not Found'}
Attempt 2: Error: 404 Not Found {'message': 'No image found with ID 8a32deca-1e5c-4d46-919d-b01b1f52e9b9

\n\n\n', 'code': '404 Not Found', 'title': 'Not Found'}
Attempt 3: Error: 404 Not Found {'message': 'No image found with ID 8a32deca-1e5c-4d46-919d-b01b1f52e9b9

\n\n\n', 'code': '404 Not Found', 'title': 'Not Found'}
```

**Comment by micafer** [comment]
This problems should be solved yes in the devel instance:
https://appsgrycap.i3m.upv.es:31443/im-dashboard-dev/
Cloud you please check it?

**Comment by BorjaEst** [comment]
Yes, as fas as I have tested it works.
I think it is automatically modifying the selected VO at "Service Credentials" right?

That is even a better solution as it solves the original error.

**Comment by micafer** [comment]
> Yes, as fas as I have tested it works.
> I think it is automatically modifying the selected VO at "Service Credentials" right?

Yes, it is what the new version does.
